from datetime import timedelta

SECRET_KEY = '12341243142542QQQ'
ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 30
ACCESS_TOKEN_EXPIRE_DELTA = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)

OAUTH2_TOKEN_URL = "/auth/token"