version: '3.7'

services:
  user_service:
    build: 
      context: ./user_service
      dockerfile: Dockerfile 
    ports:
      - 8000:8000
    networks:
      - arch-network
  project_service:
    build:
      context: ./project_service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"
    external: false